### ISSUE TITLE
您好，node项目中运行，import报错。不能直接使用require导入

### ISSUE THREAD

**Issue by yuanhuanwebfront** [wangweianger/mysqls#13]
![image](https://user-images.githubusercontent.com/20898808/103627372-786cd400-4f78-11eb-8cb1-6ac45578c9ec.png)

**Comment by yuanhuanwebfront** [comment]
已处理  导入build目录下的文件就可以了

**Comment by wangweianger** [comment]
你好 确实是有问题的，这边已经修复！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangweianger/mysqls"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午5:07
收件人:&nbsp;"wangweianger/mysqls"<mysqls@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wangweianger/mysqls] 您好，node项目中运行，import报错。不能直接使用require导入 (#13)

**Comment by yuanhuanwebfront** [comment]
> 你好 确实是有问题的，这边已经修复！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wangweianger/mysqls" <notifications@github.com&gt;; 发送时间:&nbsp;2021年1月5日(星期二) 下午5:07 收件人:&nbsp;"wangweianger/mysqls"<mysqls@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[wangweianger/mysqls] 您好，node项目中运行，import报错。不能直接使用require导入 (#13) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的  我这边更新下试试  感谢
